export const categories = [
  'poses',
  'ears',
  'eyebrows',
  'eyes',
  'accessories',
  'hat',
];

export const decorations = {
  'poses': [
    'Hands downArtboard 1@2x',
    'Both CenterArtboard 1@2x',
    'Hands upArtboard 1@2x',
    'Right WaveArtboard 1@2x',
  ],
  'ears': [
    'ears_default',
    'ears_in',
    'ears_out',
  ],
  'eyebrows': [
    'eyebrows_default',
    'eyebrows_angry',
    'eyebrows_distraught',
  ],
  'eyes': [
    'eyes_default',
    'eyes_down',
    'eyes_left',
    'eyes_left diagonal down',
    'eyes_left diagonal up',
    'eyes_right',
    'eyes_right diagonal down',
    'eyes_right diagonal up',
    'eyes_up',
  ],
  'accessories': [
    'empty',
    'BowtieAmpBlueArtboard 1@2x',
    'BowtieMintArtboard 1@2x',
    'BowtiePinkArtboard 1@2x',
    'BowtiePurpleArtboard 1@2x',
    'BowtieTealArtboard 1@2x',
    'BowtieTurquoiseArtboard 1@2x',
    'BowtieYellowArtboard 1@2x',
    'Right BalloonArtboard 1@2x',
    'Right CoffeeArtboard 1@2x',
    'Right MicrophoneArtboard 1@2x',
    'MouthArtboard 1@2x',
    'Tux bodyArtboard 1@2x',
  ],
  'hat': [
    'empty',
    'Party HatArtboard 1@2x',
    'Ballcap GiantsArtboard 1@2x',
    'CrownArtboard 1@2x',
    'FezArtboard 1@2x',
    'HeadphonesArtboard 1@2x',
  ],
}
